server:
    port: 80

property:
    test:
        name: property depth test
propertyTest: test
propertyTestList: a,b,c

fruit:
    color-name: blue
    list:
        - name: banana
          color: yellow
        - name: apple
          color: red
        - name: water melon
          color: green
datasource:
  url: jdbc:h2:mem:testdb
spring:
  h2:
    console:
      enabled: true
      path: /h2-test